name: dom_builder
description: Generate and manipulate DOM elements (virtual or real), DSX (like JSX) and HTML declarations (Web and Native support).
version: 2.0.3
homepage: https://github.com/gmpassos/dom_builder

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html: ^0.15.0
  swiss_knife: ^3.0.7
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.9
  #test_coverage: ^0.4.3

#dependency_overrides:
#  swiss_knife:
#    path: ../swiss_knife
