name: dom_builder
description: Generate and manipulate DOM (virtual and real) elements or HTML (Web and Native support).
version: 2.0.1
homepage: https://github.com/gmpassos/dom_builder

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html: ^0.15.0
  swiss_knife: ^3.0.5
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  #test_coverage: ^0.4.3

#dependency_overrides:
#  swiss_knife:
#    path: ../swiss_knife
