name: dom_builder
description: Helpers to generate DOM elements or HTML (Web and Native support).
version: 1.0.8
homepage: https://github.com/gmpassos/dom_builder

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  html: ^0.14.0+3
  swiss_knife: ^2.5.5
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
  test_coverage: ^0.4.2
