name: dom_builder
description: Generate and manipulate DOM (virtual and real) elements or HTML (Web and Native support).
version: 1.0.18
homepage: https://github.com/gmpassos/dom_builder

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  html: ^0.14.0+3
  swiss_knife: ^2.5.14
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
  test_coverage: ^0.4.3
